root {
    consumer {
        schema_url = "http://schema-registry:8081"
        brokers = ["kafka1:9092", "kafka2:9092", "kafka3:9092"]
        topics = ["link.raw-updates"]
        group_id = "agent-consumer-v1"
        offset = "latest"
        min_bytes = 1000
        max_bytes = 10e6
        max_wait_ms = 500
        max_retries = 5
    }
    producer {
        schema_url = "http://schema-registry:8081"
        brokers = ["kafka1:9092", "kafka2:9092", "kafka3:9092"]
        updates_topic = "link.processed-updates"
        batch_size = 100
        batch_bytes = 1048576
        batch_timeout_ms = 20
        required_acks = "all"
        max_retries = 3
    }

    filter {
        stop-words = ["spam", "ads", "promo", "this is spam message"]
        excluded-authors = ["bot"]
        min-length = 20
        summarization {
            threshold =  50
        }
    }
}