root {
    telegram {
        debug = true
    }

    port = 8088
    gateway_port = 8080
     http_req_config {
       timeout = 120s
       delay = 5s
       max_delay = 30s
       delay_type = "constant"
       retries = 5
       retriable_codes = [408, 429, 500, 502, 503]
        circuit_breaker {
           min_required_calls = 10
           max_requests_half_open = 10
           closed_state_interval = 10s
           open_state_interval = 10s
           sliding_window_size = 15s
           failure_rate_threshold = 50
       }
   }
    notification_type="kafka"
    scrapper_url = "http://scrapper:8082"

    n_threads = 2
    kafka {
        schema_url = "http://schema-registry:8081"
        brokers = ["kafka1:9092", "kafka2:9092", "kafka3:9092"]
        topics = ["link.processed-updates", "reports"]
        group_id = "bot-consumer-v3"
        offset = "latest"
        min_bytes = 1000
        max_bytes = 10e6
        max_wait_ms = 500
        max_retries = 5
        dead_letter_queue="dead-letter-queue"
    }
}

