root {
    bot_url = "http://bot:8080"
    port = "8081"
    gateway_port = "8082"
    http_req_config {
        timeout = 120s
        delay = 5s
        max_delay = 30s
        delay_type = "constant"
        retries = 5
        retriable_codes = [408, 429, 500, 502, 503]
        circuit_breaker {
            min_required_calls = 10
            max_requests_half_open = 10
            closed_state_interval = 10s
            open_state_interval = 10s
            sliding_window_size = 15s
            failure_rate_threshold = 50
        }
    }
    rate_limit {
        burst = 30
        limit = 10
        ip_expiration = 10m
    }
    database {
        access_type ="query"
    }

    notification_type = "kafka"
    link_tracking{
        batch_size=200
        n_threads=4
        scheduler_interval=30
        links_old_age=60
    }
    kafka {
        schema_url = "http://schema-registry:8081"
        brokers = ["kafka1:9092", "kafka2:9092", "kafka3:9092"]
        updates_topic = "link.raw-updates"
        reports_topic = "reports"
        batch_size = 100
        batch_bytes = 1048576
        batch_timeout_ms = 20
        required_acks = "all"
        max_retries = 3
    }
    cache {
        addr = ["valkey-node-0:6379", "valkey-node-1:6379", "valkey-node-2:6379"]
        user = ""
        password = "bitnami"
        timeout=5s
        expire=10m
        use_client_side_cache = true
    }
}