// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/bot_service.proto

package bot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatID) Reset() {
	*x = ChatID{}
	mi := &file_proto_bot_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatID) ProtoMessage() {}

func (x *ChatID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bot_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatID.ProtoReflect.Descriptor instead.
func (*ChatID) Descriptor() ([]byte, []int) {
	return file_proto_bot_service_proto_rawDescGZIP(), []int{0}
}

func (x *ChatID) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type LinkUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Link          string                 `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TgChatIDS     []int64                `protobuf:"varint,4,rep,packed,name=tgChatIDS,proto3" json:"tgChatIDS,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkUpdate) Reset() {
	*x = LinkUpdate{}
	mi := &file_proto_bot_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkUpdate) ProtoMessage() {}

func (x *LinkUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bot_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkUpdate.ProtoReflect.Descriptor instead.
func (*LinkUpdate) Descriptor() ([]byte, []int) {
	return file_proto_bot_service_proto_rawDescGZIP(), []int{1}
}

func (x *LinkUpdate) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LinkUpdate) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *LinkUpdate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LinkUpdate) GetTgChatIDS() []int64 {
	if x != nil {
		return x.TgChatIDS
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_proto_bot_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bot_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_bot_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_bot_service_proto protoreflect.FileDescriptor

const file_proto_bot_service_proto_rawDesc = "" +
	"\n" +
	"\x17proto/bot_service.proto\x12\x03bot\"\x18\n" +
	"\x06ChatID\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\"p\n" +
	"\n" +
	"LinkUpdate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\ttgChatIDS\x18\x04 \x03(\x03R\ttgChatIDS\"*\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2@\n" +
	"\n" +
	"BotService\x122\n" +
	"\n" +
	"SendUpdate\x12\x0f.bot.LinkUpdate\x1a\x13.bot.UpdateResponseB\x0fZ\rpkg/proto/botb\x06proto3"

var (
	file_proto_bot_service_proto_rawDescOnce sync.Once
	file_proto_bot_service_proto_rawDescData []byte
)

func file_proto_bot_service_proto_rawDescGZIP() []byte {
	file_proto_bot_service_proto_rawDescOnce.Do(func() {
		file_proto_bot_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bot_service_proto_rawDesc), len(file_proto_bot_service_proto_rawDesc)))
	})
	return file_proto_bot_service_proto_rawDescData
}

var file_proto_bot_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_bot_service_proto_goTypes = []any{
	(*ChatID)(nil),         // 0: bot.ChatID
	(*LinkUpdate)(nil),     // 1: bot.LinkUpdate
	(*UpdateResponse)(nil), // 2: bot.UpdateResponse
}
var file_proto_bot_service_proto_depIdxs = []int32{
	1, // 0: bot.BotService.SendUpdate:input_type -> bot.LinkUpdate
	2, // 1: bot.BotService.SendUpdate:output_type -> bot.UpdateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_bot_service_proto_init() }
func file_proto_bot_service_proto_init() {
	if File_proto_bot_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bot_service_proto_rawDesc), len(file_proto_bot_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bot_service_proto_goTypes,
		DependencyIndexes: file_proto_bot_service_proto_depIdxs,
		MessageInfos:      file_proto_bot_service_proto_msgTypes,
	}.Build()
	File_proto_bot_service_proto = out.File
	file_proto_bot_service_proto_goTypes = nil
	file_proto_bot_service_proto_depIdxs = nil
}
